/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/Spaceship.glb -o Spaceship.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Spaceship(props) {
  const { nodes, materials } = useGLTF('/Spaceship.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Spaceship_BarbaraTheBee.geometry} material={materials.Atlas} scale={100} />
    </group>
  )
}

useGLTF.preload('/Spaceship.glb')
